---
title: 'More than Likes: A bla bla of bla bla with bla bla'
subtitle: |
  | 
  | University of Copenhagen
  | `r source("scripts/utils.R")`
  | Student IDs:
  | XXXxxx
  | XXXxxx
  | Master's Thesis
  | Number of characters: xxxxxxxxx
  | `r # maybe for word count: RmdWords("paper.Rmd")$num_words`
output:
  pdf_document:
    keep_tex: yes
    latex_engine: pdflatex
    number_sections: yes
  html_document: 
    number_sections: yes
    toc: true
    toc_depth: 2
header-includes:
- \usepackage{amsmath} # format math stuff
- \usepackage{booktabs} # makes table nicer
- \usepackage{lastpage} # be able to count total pages
- \usepackage{fancyhdr} # header/footer
- \pagestyle{fancy} # header/footer
- \fancyhead{} # remove header
- \renewcommand{\headrulewidth}{0pt} # remove header
- \fancyfoot[CO,CE]{Page \thepage\ of \pageref{LastPage}} # add Page X of Y
- \usepackage{floatrow} # position tables and figures correctly
- \floatsetup[figure]{capposition=top} # position tables and figures correctly
- \floatsetup[table]{capposition=top} # position tables and figures correctly
- \usepackage{setspace} # controls line spacing
bibliography: references.bib # add bibliography
csl: chicago-author-date # choose chicago citation style
link-citations: yes # add links in citations
nocite: '*' # add all used citations
---

```{r setup, include=FALSE}
source("scripts/config.R")
```


\pagebreak
<!-- TC:ignore -->
```{=latex}
\setcounter{tocdepth}{2}
\tableofcontents
```
<!-- TC:endignore --> 

\pagebreak

# Introduction
<!-- Word count: approx. 400  -->
<!-- Word count now: 426  -->

\onehalfspacing <!-- OBS: We use double spacing here. Could also be changed to \onehalfspacing -->



\pagebreak
# Data and Method



\pagebreak 
# Results and discussion




<!-- TC:ignore -->
```{r, echo=FALSE, results='asis'}
source("scripts/regression.R")
```
<!-- TC:endignore -->



\pagebreak
# Conclusion


\pagebreak

<!-- TC:ignore -->

# References

<div id="refs"></div>

\pagebreak

# Appendix




